### ISSUE TITLE
Add support for Scala 2.13

### ISSUE THREAD

**Issue by dragisak** [algolia/algoliasearch-client-scala#554]

**Comment by aseure** [comment]
Thank you again for your contribution @dragisak.

Just to let you know that Scala 2.13 is now supported as of v1.35.0 of the Algolia API client. It's already deployed on Sonatype and should be available for download in the next few hours on Maven Central. Full ChangeLog of v1.35.0 is [available here](https://github.com/algolia/algoliasearch-client-scala/pull/571).

cc @benwaffle @jlogeart since you've shown interest for Scala 2.13 support.
